name: run api testing
on:
    push:
        branches: [dev, stage, master]
    pull_request:
        branches: [master]

jobs:
    api-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        services:
            postgres:
                image: postgres:12-alpine
                env:
                    POSTGRES_USER: root
                    POSTGRES_PASSWORD: privatepassword
                    POSTGRES_DB: CRUD_DB
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install

            - name: API testing
              run: npm run test